name: qrscanner_zxing
description: Android-only QR Scanner plugin based on zxing and CameraX API's
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.yubico.authenticator.flutter_plugins.qrscanner_zxing
        pluginClass: QRScannerZxingPlugin