name: macOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.4

    - name: Set up CocoaPods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        podfile-path: macos/Podfile.lock

    - name: Install dependencies
      run: |
        brew update
        brew install swig
        python -m pip install --upgrade pip
        pip install poetry

    - name: Build the Helper
      run: ./build-helper.sh

    - uses: subosito/flutter-action@v2
      with:
        channel: master
        flutter-version: 3.24.0
    - run: flutter config --enable-macos-desktop
    - run: flutter --version

    - name: Build the app
      run: flutter build macos --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/macos
