name: macOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up CocoaPods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        podfile-path: macos/Podfile.lock

    - uses: subosito/flutter-action@v2
      with:
        channel: master
        flutter-version: 3.24.0
    - run: flutter config --enable-macos-desktop
    - run: flutter --version

    - name: Build the app
      run: flutter build macos --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/macos
